### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Zayelion** [Snarkie/YGOProAIScript#3]
Could you move the documentation from the ygopro.co forum to the repo as md files?

**Comment by Snarkie** [comment]
Sure. Which documentation are you referring to? The tutorial?

**Comment by Zayelion** [comment]
Yes please. I'm specifically after any variables that are not created by the scripts but are made available  from the application. I'm trying to create another shell for the scripts to run in.

**Comment by Snarkie** [comment]
Not sure, when I'll get around to do that. But in the meantime, all of the variables made available by the system should be documented in the "ai-template.lua" file, which is included in the program. The standalone file might not be available, you might need to download the latest update files or something.

**Comment by Zayelion** [comment]
From what I can see there are the following that I need explanations for :
- `AI` object, seems to have a bunch of methods attached.
- `Duel` object

**Comment by Snarkie** [comment]
The AI methods are documented in the template, including sample usage. Starting at line 80 on my end. Most of these are very straight forward, just providing basic info or lists of cards. What else do you need?

Duel is not specific to the AI, it is available for card scripts as well:
https://github.com/Fluorohydride/ygopro-core/blob/master/interpreter.cpp
I do not know, how exactly your client is set up, but since these are core YGOPro functionality and not specific to Percy's adaptation, the Duel object should exist and be usable on your end without any further action required.

**Comment by Zayelion** [comment]
I'm writing an AI similiar to `windbot` it acts as a client and connects to a duel, it doesnt have access to the Duel object only whats passed to it via the onSelect and onYesOrNo type questions.It can read the DB also but thats really it.

Its not a YGOPro so much as a question parser.

**Comment by Snarkie** [comment]
The problem with the Duel object and the card script stuff in general would be, that there is very limited documentation for all of these, at least from what I was able to find. Most of the stuff I found out by trial&error or copy&paste from card scripts. If you are looking for a complete documentation, I can hardly help you.

I did include the template, and the AI scripting tutorial from the forums as md files, that should have most of the stuff I am aware of. Although, including the template as .md instead of .lua might not make a lot of sense. No idea, what the general consensus dictates here. Currently fixing the formatting for the tutorial, getting used to markdown. 

Not sure, if the tutorial is exactly what you're looking for. It's very verbose, and mostly aimed at people with not too much coding experience. It doesn't really have that much information on the card script objects either. But you did probably read it before. 

Anyway, if this was not, what you had in mind, notify me.
